In [1]:
import whatsapp_bot as wpb
import pandas as pd
import numpy as np

In [2]:
### datos de celular para el test
#data={'phone_numbers':[965992236,954302730, 965992236, 981827783, 993453473, 966504433, 934091769],"envio": 0}
data={'phone_numbers':[965992236, 981827783, 959658118, 954302730],"envio": 0,'Estado':["Pendiente","En proceso","Pendiente","En proceso"],'Tipologia':["2","2","2","2"]}
df=pd.DataFrame(data)
df["msj"]="Prueba1"

df=df.query("Estado=='Pendiente'").reset_index()
# df=df.query('Estado=="En proceso" & Tipologia=="2"').reset_index()
df

   index  phone_numbers  envio     Estado Tipologia      msj
0      0      965992236      0  Pendiente         2  Prueba1
1      2      959658118      0  Pendiente         2  Prueba1

In [2]:
url_report_1="https://docs.google.com/spreadsheets/d/1hnbiESNhHTwZhxFd50VmGsGSPgZbvYST/edit#gid=948696469"
url_report_2="https://docs.google.com/spreadsheets/d/1wmAax2awqW76YxeLGtvtLtacFQph7rxn/edit#gid=1340043171"
r1=wpb.change_report(url_report_1,url_report_2)

envio                      0.0   1.0
statusdes  statusdes_2
PENDIENTE  PENDIENTE    1940.0  18.0
           REGISTRADO      5.0   NaN
PROCESO    PROCESO      3114.0   NaN
           REGISTRADO     12.0   NaN
REGISTRADO REGISTRADO   2433.0   NaN

In [25]:
print(wpb.get_excel_txt('https://docs.google.com/spreadsheets/d/1DLrgfIjw0ekiazcohkX2YF_8Rsoa8OYi-0DOKZUIqNo/edit#gid=0', seguimiento_text=True, estado="PROCESO", tipologia=2),"\n")
wpb.cleaning_report_status_df(url=r1, estado="PROCESO", tipologia=2, var_start=0, var_end=5)

                                                text enviar
4  Director/a, recuerda que para culminar el regi...     SI
5  Recuerda que puedes revisar nuestros videos tu...     SI

,index_o,cod_unico,CODDRE,DRE,codooii,DNIDIRECTIVO,phone_number,statusdes,sec_gen,sec_met,envio,tipo
0,60322,16723851672377000016757,250000,DRE UCAYALI,250001,00016757,961934795,PROCESO,VERDADERO,FALSO,0.0,2
1,56084,16005351600576000074909,250000,DRE UCAYALI,250001,00074909,988081670,PROCESO,VERDADERO,FALSO,0.0,2
2,24899,00836833139375000092246,250000,DRE UCAYALI,250001,00092246,968489679,PROCESO,VERDADERO,FALSO,0.0,2
3,1332,00058424300093561,250000,DRE UCAYALI,250001,00093561,927013073,PROCESO,VERDADERO,FALSO,0.0,2
4,30322,01625417171812100104899,250000,DRE UCAYALI,250001,00104899,971497936,PROCESO,VERDADERO,FALSO,0.0,2

In [ ]:
url_msj='https://docs.google.com/spreadsheets/d/1DLrgfIjw0ekiazcohkX2YF_8Rsoa8OYi-0DOKZUIqNo/edit#gid=0'

wpb.execute_bot(url_bd=r1, url_sms=url_msj,
                user="gestionmatricula@gmail.com",
                pass_user="qwerty",
                seguimiento=True,
                estado_segui="Pendiente",
                test=True)

In [7]:
## información de la función
wpb.execute_bot?

Signature:
wpb.execute_bot(
    url_bd,
    url_sms,
    dre_name=None,
    ugel_cod=None,
    var_start=None,
    var_end=None,
    user=None,
    pass_user=None,
    google_drive=False,
    test=False,
    seguimiento=False,
    estado_segui=None,
    tipologia_segui=None,
    first_report=False,
)
Docstring:
#Docstring:
  Ejecuta el bot para el envio automático de mensajes de whatsapp usando el servicio de Callbell y los usuarios creados para Matrícula Digital.
  Ejecutado de forma local, abre una nuevo navegador de google Chrome en modo incognito.
  Ejecutado desde google Drive, ejecuta el código en modo 'headless', sin necesidad de abrir una ventana del navegador.

Parameters
  ----------
  url_bd: str, url de la base de datos (BD) de directores alojada en el drive del proyecto.
      Si se desea utilizar otra BD de números telefónicos, la base de datos debe tener como mínimo las siguientes variables:
      ['DRE', 'UGEL', 'phone_numbers','codooii']
  url_sms: str, url de la BD de los textos que serán envíados
  dre_name: str, default None. Es el nombre de la DRE por la cual se quiere filtrar. El nombre deber ser igual al de la BD de url_bd.
      En caso no se introduzca un valor, se carga toda la BD.
  ugel_cod: str, default None. Es el código de identificación (codooii) de la UGEL por la cual se quiere filtra la BD.
      Esta variable debe estar en formato texto. Además, el código de la UGEL debe ser igual al de la BD de url_bd.
      En caso no se introduzca un valor, se carga toda la BD.
  var_start: int, default None. Es la fila de inicio por la cual se quiere filtra la BD.
      Tener en consideración que en Python la primera fila de una BD corresponde al valor 0 y no al valor 1.
      Por lo tanto, si se desea filtrar desde la fila 10, el valor de var_start será 9.
  var_end: int, default None. Es la fila de término por la cual se quiere filtra la BD.
      Tener en consideración que en Python la primera fila de una BD corresponde al valor 0 y no al valor 1.
      Si se desea filtrar desde la fila 50 hasta la fila 100 los valores de var_start y var_end serán:
          var_start=49, var_end=99
  user: str, default None. Es el correo electrónico con el que se ingresará a la web de Callbell.
  pass_user: str, default None. Es el password con el que se ingresará a la web de Callbell.
  google_drive: boolen, default False. Es True cuando el bot se ejecute desde la aplicación colab de google drive.
  test: boolen, default False. Aplica en caso se desea hacer un test usando una BD de teléfonos de prueba.


File:      c:\users\guillermo\desktop\python\06. matricula digital\whatsappy\whatsapp_bot\driver_whatsapp.py
Type:      function

In [2]:
url_directivos="https://docs.google.com/spreadsheets/d/1-biLN4-QAVIL6oV9dfFMpgiNC2Itbs2V/edit#gid=2036506774"
url_msj='https://docs.google.com/spreadsheets/d/1DLrgfIjw0ekiazcohkX2YF_8Rsoa8OYi-0DOKZUIqNo/edit#gid=0'

bf_r=wpb.execute_bot(url_bd=url_directivos, url_sms=url_msj,
                ugel_cod="150102",
                user="gestionmatricula@gmail.com",
                pass_user="qwerty",
                var_start=500,
                var_end=510,
                test=False)

El número de filas de la BD es:  10

In [314]:
ruta_local=r'C:\Users\Guillermo\Desktop\Python\06. Matricula Digital\bases de datos'

df5=pd.read_excel(ruta_local+"\\Passport_01mar_Padrón_09abr_codmod_Metas_2004.xlsx", converters={0:str, 2:str,5:str,6:str,7:str,8:str,13:str,14:str})

for p in ['cm_ini','cm_pri', 'cm_sec']:
    df5[p]=df5[p].replace(np.nan,"0")

df5["cod_unico"]=df5.cm_ini+df5.cm_pri+df5.cm_sec+df5.DNIDIRECTIVO
#df5[df5.duplicated(["cod_unico"], keep=False)][['CODDRE', 'DRE', 'CODUGEL','DNIDIRECTIVO','cod_unico','match','TELEFONOPERSONAL', 'statusdes','sec_gen', 'sec_met']]

df6=df5.query('cod_unico!=""', engine='python').sample(300)
for p in ['cm_ini','cm_pri', 'cm_sec']:
    df6[p]=df6[p].replace("0",np.nan)

df6['statusdes']="Registrado"
df6['keep']=1
df7=pd.concat([df5,df6])
df7=df7.sort_values('keep').drop_duplicates('cod_unico', keep='first')#.sort_values('keep')#[['CODDRE', 'DRE', 'CODUGEL','DNIDIRECTIVO','cod_unico','match','TELEFONOPERSONAL', 'statusdes','sec_gen', 'sec_met','keep']]
df7[['CODDRE', 'DRE', 'CODUGEL', 'UGEL', 'CEN_EDU', 'CODLOCAL', 'cm_ini',
       'cm_pri', 'cm_sec', 'APELLIDOPATERNO', 'APELLIDOMATERNO', 'NOMBRES',
       'TIPODOCUMENTO', 'DNIDIRECTIVO', 'TELEFONOPERSONAL',
       'CORREOELECTRONICO', 'CORREOELECTRONICOvalidado', 'statusdes', 'match',
       'sec_gen', 'sec_met', 'tm_ini', 'tm_pri', 'tm_sec', 'tm_tot',
       'n_ie_reg', 'n_ie_epr', 'n_ie_pen']].to_excel(ruta_local+"\\Passport_01mar_Padrón_09abr_codmod_Metas_2404.xlsx", index=False)

In [45]:
def clean_numbers(df_o):
    df=df_o.copy()
    df["phone_l"]=df.phone_numbers.str.strip().str.len()
    df=df.query('phone_l==9 & phone_numbers!="999999999" & phone_numbers!="123456789"', engine='python').copy()
    df['phone_numbers']=df['phone_numbers'].astype(int)
    del df["phone_l"]
    
    return df

def open_clean_var_seguimiento(url):
    text = url.rsplit('/', 1)[0]
    df=pd.read_csv(text+"/export?format=csv", skiprows=1, usecols=[3,4,5,6,7,8,9,10,11,23,52,53,57,58,59], converters={3:str,5:str,6:str,7:str,8:str,9:str,10:str,11:str,52:str,53:str})
    df.columns=['CODDRE','DRE','codooii','ugel','cod_local','cod_unico_0','cm_ini','cm_pri', 'cm_sec','alerta','phone_numbers','DNIDIRECTIVO','statusdes','sec_gen', 'sec_met']
    for p in ['cm_ini','cm_pri', 'cm_sec']:
        df[p]=df[p].replace("","0", regex=True)
    df["cod_unico"]=df.cm_ini+df.cm_pri+df.cm_sec+df.DNIDIRECTIVO
    df['alerta']=df['alerta'].str.upper().str.strip().replace("Í","I",regex=True)
    
    return df

def cleaning_report_status_df(url, estado, dre_name=None, ugel_cod=None, tipologia=None,var_start=None, var_end=None, test=False, first_rep=False):
    if test==True:
        df_3=url.copy()
    else:
        if first_rep==True:
            df_3=open_clean_var_seguimiento(url)[['CODDRE', 'DRE', 'codooii','cod_unico','DNIDIRECTIVO','phone_numbers', 'statusdes','sec_gen', 'sec_met','alerta']].copy()
            df_3["envio"]=0
        else:
            df_3=url.query('envio==0').copy()
        
        if dre_name!=None:
            df_3=df_3[df_3.dre==dre_name].copy()
        else:
            if ugel_cod!=None:
                df_3=df_3[df_3.codooii==ugel_cod].copy()
            else:
                df_3=df_3.copy()
        
        if estado=="PENDIENTE":
            df_3=df_3.query('statusdes==@estado', engine='python').copy()
        if estado=="PROCESO":
            ##creamos la tipología
            df_3['tipo']=0
            df_3['tipo']=np.where((df_3.sec_gen=="FALSO") &(df_3.sec_met=="VERDADERO"),1,df_3.tipo)
            df_3['tipo']=np.where((df_3.sec_gen=="VERDADERO") &(df_3.sec_met=="FALSO"),2,df_3.tipo)
            df_3['tipo']=np.where((df_3.sec_gen=="VERDADERO") &(df_3.sec_met=="VERDADERO"),3,df_3.tipo)
            df_3['tipo']=np.where((df_3.alerta=="SI"), 4, df_3.tipo)
            ## filtramos
            df_3=df_3.query('statusdes==@estado & tipo==@tipologia', engine='python')
        elif estado=="TODOS":
            ##creamos la tipología
            df_3['tipo']=0
            df_3['tipo']=np.where((df_3.alerta=="SI"), 4, df_3.tipo)
            ## filtramos
            df_3=df_3.query('tipo==@tipologia', engine='python')
            
        
        ## limpiamos los telefonos que no corresponden a números reales
        df_3=clean_numbers(df_3).copy()     
        df_3=df_3.sort_values("DNIDIRECTIVO").iloc[var_start:var_end].reset_index().rename({"index":"index_o"},axis=1)
        
    return df_3


def get_excel_txt(url, seguimiento_text=False, estado=None, tipologia=None):
    text = url.rsplit('/', 1)[0]
    if seguimiento_text==True:       
        ## cleaning the data
        df=pd.read_csv(text+"/export?format=csv"+"&gid="+str(1620900866))
        df['enviar']=df['enviar'].str.upper().str.strip().replace(["Ï","Í","Ì"],"I",regex=True)
        if estado=="PENDIENTE":
            df['Estado']=df['Estado'].str.upper().str.strip()
            df=df[(df.Estado==estado)&(df.enviar=='SI')].copy()
        if estado=="TODOS":
            df=df[(df.Tipologia==str(tipologia))&(df.enviar=='SI')].copy()
        else:            
            df=df[(df.Tipologia==str(tipologia))&(df.enviar=='SI')].copy()
            if tipologia ==0:
                df=df.iloc[0:1]
        
        df["text"]=df["text"]+" \n"
        df=df.iloc[:,4:].copy()
        
    else:        
        ## cleaning the data
        df=pd.read_csv(text+"/export?format=csv")

        df.columns=['text','enviar']
        df['enviar']=df['enviar'].str.upper().str.strip().replace(["Ï","Í","Ì"],"I",regex=True)
        df=df[(df.text.notna())&(df.enviar=='SI')].copy()
        df["text"]=df["text"]+" \n"
        
    return df

In [ ]:
df=cleaning_report_status_df(url="https://docs.google.com/spreadsheets/d/1k8LDr_niCN9lWJBGAQVSIv8Xb_xH5ppa/edit#gid=166209892",
                          estado="TODOS",
                          tipologia=0,
                          first_rep=True)
df=df.query('')

,index_o,CODDRE,DRE,codooii,cod_unico,DNIDIRECTIVO,phone_numbers,statusdes,sec_gen,sec_met,alerta,envio,tipo
0,18770,250000,DRE UCAYALI,250001,00806562000001179,00001179,929620061,NaN,NaN,NaN,NO,0,0
1,18840,250000,DRE UCAYALI,250001,00584128160265500001338,00001338,943442125,NaN,NaN,NaN,NO,0,0
2,18924,250000,DRE UCAYALI,250001,00923664160073300007670,00007670,984188666,NaN,NaN,NaN,NO,0,0
3,18914,250000,DRE UCAYALI,250001,00175356500013009,00013009,961083108,NaN,NaN,NaN,NO,0,0
4,18848,250000,DRE UCAYALI,250001,06662140000013619,00013619,961689307,NaN,NaN,NaN,NO,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12430,11345,150101,DRE LIMA METROPOLITANA,150103,04967520080645026,80645026,989696658,NaN,NaN,NaN,NO,0,0
12431,17625,210000,DRE PUNO,210012,00158413580668290,80668290,944508465,NaN,NaN,NaN,NO,0,0
12432,1617,040000,GRE AREQUIPA,040005,00639187080670780,80670780,983818418,NaN,NaN,NaN,NO,0,0
12433,18743,250000,DRE UCAYALI,250001,00160060080672402,80672402,974126298,NaN,NaN,NaN,NO,0,0
12434,17160,210000,DRE PUNO,210006,00229021080689848,80689848,976956842,NaN,NaN,NaN,NO,0,0

In [47]:
%%timeit
cleaning_report_status_df(url="https://docs.google.com/spreadsheets/d/1k8LDr_niCN9lWJBGAQVSIv8Xb_xH5ppa/edit#gid=166209892",
                          estado="TODOS",
                          tipologia=4,
                          first_rep=True,
                          ugel_cod="150108")

6.02 s ± 1.05 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [36]:
get_excel_txt(url="https://docs.google.com/spreadsheets/d/1DLrgfIjw0ekiazcohkX2YF_8Rsoa8OYi-0DOKZUIqNo/edit#gid=0",
              seguimiento_text=True, estado="TODOS", tipologia=4)

                                                 text enviar
11  Director/a, revisa la información que registra...     SI